export const templates = {
  phraseGroups: {
    style: {
      phrases: [
        { phrase: 'high-quality', weight: 1.2 },
        { phrase: 'visually compelling', weight: 1.0 },
        { phrase: 'cohesive and well-composed', weight: 1.0 },
        { phrase: 'photorealistic', weight: 0.9 },
        { phrase: 'cinematic', weight: 0.9 },
        { phrase: 'editorial style', weight: 0.9 },
        { phrase: 'concept art', weight: 0.8 },
        { phrase: 'illustration', weight: 0.8 },
        { phrase: '3D render', weight: 0.7 },
        { phrase: 'painterly', weight: 0.7 },
        { phrase: 'surreal', weight: 0.6 },
      ],
    },
    lighting: {
      phrases: [
        { phrase: 'soft natural light', weight: 1.0 },
        { phrase: 'dramatic lighting', weight: 0.9 },
        { phrase: 'golden hour', weight: 0.8 },
        { phrase: 'studio lighting', weight: 0.9 },
        { phrase: 'rim lighting', weight: 0.7 },
        { phrase: 'volumetric light', weight: 0.7 },
        { phrase: 'soft diffused lighting', weight: 0.9 },
        { phrase: 'neon accent lighting', weight: 0.6 },
        { phrase: 'dreamy glow', weight: 0.7 },
      ],
    },
    camera: {
      phrases: [
        { phrase: 'sharp subject focus', weight: 1.0 },
        { phrase: 'shallow depth of field', weight: 0.9 },
        { phrase: 'high dynamic range', weight: 0.8 },
        { phrase: 'bokeh', weight: 0.7 },
        { phrase: 'dynamic perspective', weight: 0.7 },
        { phrase: 'wide angle perspective', weight: 0.6 },
      ],
    },
    composition: {
      phrases: [
        { phrase: 'thoughtful composition', weight: 1.0 },
        { phrase: 'rule of thirds', weight: 0.8 },
        { phrase: 'leading lines', weight: 0.7 },
        { phrase: 'symmetrical framing', weight: 0.6 },
        { phrase: 'dynamic angle', weight: 0.7 },
        { phrase: 'candid moment framing', weight: 0.6 },
        { phrase: 'negative space', weight: 0.6 },
      ],
    },
    detail: {
      phrases: [
        { phrase: 'high detail', weight: 1.1 },
        { phrase: 'texture-rich', weight: 0.9 },
        { phrase: 'fine details', weight: 0.9 },
        { phrase: 'crisp edges', weight: 0.8 },
      ],
    },
    colorMood: {
      phrases: [
        { phrase: 'vibrant colors', weight: 0.8 },
        { phrase: 'muted tones', weight: 0.7 },
        { phrase: 'warm color palette', weight: 0.7 },
        { phrase: 'cool color palette', weight: 0.7 },
        { phrase: 'high contrast', weight: 0.7 },
        { phrase: 'soft pastel palette', weight: 0.6 },
        { phrase: 'moody color grading', weight: 0.6 },
      ],
    },
    environment: {
      phrases: [
        { phrase: 'background that complements the subject', weight: 1.0 },
        { phrase: 'contextual setting', weight: 0.8 },
        { phrase: 'subtle atmosphere', weight: 0.8 },
        { phrase: 'simple studio backdrop', weight: 0.8 },
        { phrase: 'cinematic environment', weight: 0.7 },
      ],
    },
    stationery: {
      phrases: [
        { phrase: 'clean white background with ample whitespace and margins', weight: 1.3 },
        { phrase: 'professional typographic hierarchy with clear logo placement', weight: 1.2 },
        { phrase: 'logo placed in the top-left header only; do NOT center the logo', weight: 1.6 },
        { phrase: 'header with clear top-left logo and optional top-right accent band or corner flourish', weight: 1.4 },
        { phrase: '12mm safe margins for print; avoid placing important elements within 12mm of any edge', weight: 1.5 },
        { phrase: 'provide a monochrome (black-on-white) logo variant for print', weight: 1.4 },
        { phrase: 'subtle diagonal watermark or light pattern in the lower-right quadrant for brand texture', weight: 1.0 },
        { phrase: 'footer row with contact details and minimal separators, aligned right or centered', weight: 1.2 },
        { phrase: 'generous page margins and safe area for printing; avoid placing important elements within 12mm of edges', weight: 1.3 },
        { phrase: 'accent stripe or corner graphic in brand color that complements the logo', weight: 1.1 },
        { phrase: 'balanced margins with top-left logo placement', weight: 1.1 },
        { phrase: 'vector-ready logo, scalable and monochrome-friendly', weight: 1.1 },
        { phrase: 'print-ready layout, CMYK friendly, 300 DPI suggestion', weight: 0.9 },
        { phrase: 'minimal, elegant color palette suited for corporate stationery', weight: 1.0 },
        { phrase: 'balanced composition with generous negative space', weight: 1.0 },
      ],
    },
  },
} as const;
